using Content.Shared.Light.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Light;

[GenerateTypedNameReferences]
public sealed partial class FlashlightMaintenanceWindow : FancyWindow
{
    public event Action<float>? OnFocusChanged;
    public event Action<FlashlightModule>? OnServiceModule;

    public FlashlightMaintenanceWindow()
    {
        RobustXamlLoader.Load(this);

        FocusSlider.OnReleased += _ => OnFocusChanged?.Invoke(FocusSlider.Value / 100f);
        LensButton.OnPressed += _ => OnServiceModule?.Invoke(FlashlightModule.Lens);
        EmitterButton.OnPressed += _ => OnServiceModule?.Invoke(FlashlightModule.Emitter);
        ContactsButton.OnPressed += _ => OnServiceModule?.Invoke(FlashlightModule.Contacts);
        HeatSinkButton.OnPressed += _ => OnServiceModule?.Invoke(FlashlightModule.HeatSink);
    }

    public void UpdateState(FlashlightMaintenanceBoundUserInterfaceState state)
    {
        FocusSlider.SetValueWithoutEvent(state.Focus * 100f);
        FocusValue.Text = $"{Percent(state.Focus)}%";
        ProjectionLabel.Text = Loc.GetString(
            "flashlight-maintenance-window-projection",
            ("radius", state.ProjectedRadius.ToString("0.0")),
            ("energy", state.ProjectedEnergy.ToString("0.0")));

        StatusLabel.Text = state.Overheated
            ? Loc.GetString("flashlight-maintenance-window-overheated")
            : Loc.GetString("flashlight-maintenance-window-status");

        LensLabel.Text = Loc.GetString("flashlight-maintenance-window-lens", ("value", Percent(state.LensIntegrity)));
        EmitterLabel.Text = Loc.GetString("flashlight-maintenance-window-emitter", ("value", Percent(state.EmitterIntegrity)));
        ContactsLabel.Text = Loc.GetString("flashlight-maintenance-window-contacts", ("value", Percent(state.ContactIntegrity)));
        HeatSinkLabel.Text = Loc.GetString("flashlight-maintenance-window-heatsink", ("value", Percent(state.HeatSinkIntegrity)));
        HeatLabel.Text = Loc.GetString("flashlight-maintenance-window-heat", ("value", Percent(state.Heat)));
    }

    private static int Percent(float value)
    {
        return (int) MathF.Round(Math.Clamp(value, 0f, 1f) * 100f);
    }
}
