using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.PlayerTab;

[GenerateTypedNameReferences]
public sealed partial class PlayerTabEntry : PanelContainer
{
    public PlayerTabEntry(
        PlayerInfo player,
        StyleBoxFlat styleBoxFlat,
        AdminPlayerTabColorOption colorOption,
        AdminPlayerTabRoleTypeOption roleSetting,
        AdminPlayerTabSymbolOption symbolSetting)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        UsernameLabel.Text = player.Username;
        if (!player.Connected)
            UsernameLabel.StyleClasses.Add("Disabled");
        JobLabel.Text = player.StartingJob;

        var colorRoles = false;
        switch (colorOption)
        {
            case AdminPlayerTabColorOption.Off:
                break;
            case AdminPlayerTabColorOption.Character:
                break;
            case AdminPlayerTabColorOption.Roletype:
                colorRoles = true;
                break;
            default:
            case AdminPlayerTabColorOption.Both:
                colorRoles = true;
                break;
        }

        CharacterLabel.Text = player.CharacterName;
        if (player.IdentityName != player.CharacterName)
            CharacterLabel.Text += $" [{player.IdentityName}]";

        SponsorLabel.Text = player.IsSponsor ? player.SponsorTitle : ""; // Sunrise-Sponsors

        RoleTypeLabel.Text = Loc.GetString("player-tab-role-redacted");
        if (colorRoles)
            RoleTypeLabel.FontColorOverride = Color.FromHex("#8D7A62");
        BackgroundColorPanel.PanelOverride = styleBoxFlat;
        OverallPlaytimeLabel.Text = player.PlaytimeString;
    }
}
