using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Radio.Ui;

[GenerateTypedNameReferences]
public sealed partial class HandheldRadioWindow : DefaultWindow
{
    private int _max = 36;
    private int _min = 1;

    public HandheldRadioWindow()
    {
        RobustXamlLoader.Load(this);
        ChannelLineEdit.OnTextChanged += OnValueChanged;
    }

    public void SetState(int? selectedChannel, int min, int max)
    {
        _min = min;
        _max = max;

        CurrentChannel.Text = selectedChannel is { } channel
            ? Loc.GetString("ui-handheld-radio-current", ("channel", channel))
            : Loc.GetString("ui-handheld-radio-current-null");

        MinimumChannel.Text = Loc.GetString("ui-handheld-radio-min", ("channel", _min));
        MaximumChannel.Text = Loc.GetString("ui-handheld-radio-max", ("channel", _max));
        ChannelLineEdit.Text = selectedChannel?.ToString() ?? "null";
        Validate();
    }

    private void OnValueChanged(LineEdit.LineEditEventArgs args)
    {
        Validate();
    }

    private void Validate()
    {
        if (string.Equals(ChannelLineEdit.Text.Trim(), "null", StringComparison.OrdinalIgnoreCase))
        {
            ApplyButton.Disabled = false;
            return;
        }

        ApplyButton.Disabled = !int.TryParse(ChannelLineEdit.Text, out var channel)
            || channel < _min
            || channel > _max;
    }
}
